Repository 20-2-SKKU-OSS/2020-2-OSS-2, pull requests merged in 2020-12, with the labels that each got.

#35 Wonchul shin
  index.js
  utils/cli.js
  utils/cliKor.js
Labels: enhancement

#34 [UPDATE] getCountry.js의 콘솔 로그 for loop 밖으로 빼고 news를 테이블 삽입
  index.js
  utils/getCountry.js
  utils/news.js
Labels: enhancement

#36 [fix] 크롤링 관련 형식 수정 및 undefined 주소 문제 해결
  utils/news.js
Labels: bug

#40 [ADD] 다중 국가 출력 소트 기능
  utils/getCountry.js
Labels: bug, enhancement
